# Generated by Django 5.0.4 on 2024-05-22 06:18

import archeomap.models.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, unique=True, verbose_name='Археолог')),
            ],
            options={
                'verbose_name': 'Список археологов',
                'verbose_name_plural': 'Cписок археологов',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_category_value', models.CharField(choices=[('Unknown', 'Unknown'), ('Санитарные захоронения', 'Санитарные захоронения'), ('Исторические кладбища', 'Исторические кладбища'), ('Культовые сооружения (Храмы\\Церкви\\Часовни)', 'Культовые сооружения (Храмы\\Церкви\\Часовни)'), ('Клады\\случайные находки', 'Клады\\случайные находки'), ('Крепости\\укрепления\\фортификационные сооружения', 'Крепости\\укрепления\\фортификационные сооружения'), ('Жилые постройки', 'Жилые постройки'), ('Общественные постройки', 'Общественные постройки'), ('Хозяйственные постройки', 'Хозяйственные постройки'), ('Промышленные постройки', 'Промышленные постройки'), ('Морские постройки', 'Морские постройки'), ('Инфраструктурные объекты', 'Инфраструктурные объекты'), ('Парки\\архитектура малых форм', 'Парки\\архитектура малых форм'), ('Подводные памятники', 'Подводные памятники'), ('Дворцы', 'Дворцы'), ('Участок культурного слоя', 'Участок культурного слоя'), ('Памятники доисторической эпохи', 'Памятники доисторической эпохи'), ('Памятники Железного века и Средневековья', 'Памятники Железного века и Средневековья')], max_length=255, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Классификация памятника',
                'verbose_name_plural': 'Классификация памятника',
            },
        ),
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_category_value', models.CharField(choices=[('NONE', 'NONE'), ('Памятники с обозначением на местности', 'Памятники с обозначением на местности'), ('Уникальные археологические памятники', 'Уникальные археологические памятники'), ('Памятники, напрямую связанные с историческими личностями', 'Памятники, напрямую связанные с историческими личностями'), ('Первые археологические раскопки в Петербурге', 'Первые археологические раскопки в Петербурге'), ('Захоронения первостроителей Петербурга', 'Захоронения первостроителей Петербурга'), ('Место сражения', 'Место сражения')], max_length=255, unique=True, verbose_name='Кастомная категория')),
            ],
            options={
                'verbose_name': 'Кастомная категория',
                'verbose_name_plural': 'Кастомная категория',
            },
        ),
        migrations.CreateModel(
            name='Dating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_value', models.CharField(choices=[('Unknown', 'Unknown'), ('VI тыс. до н.э ', 'VI тыс. до н.э '), ('II - нач. I тыс. до н.э', 'II - нач. I тыс. до н.э'), ('I тыс. до н.э - кон. I тыс. н.э', 'I тыс. до н.э - нач I тыс. н.э'), ('кон. I тыс. н.э - нач. XVII в.', 'кон. I тыс. н.э - нач. XVII в.'), ('1 пол. XVII в.', '1 пол. XVII в.'), ('2 пол. XVII в.', '2 пол. XVII в.'), ('1 пол. XVIII в.', '1 пол. XVIII в.'), ('2 пол. XVIII в.', '2 пол. XVIII в.'), ('1 пол. XIX в.', '1 пол. XIX в.'), ('2 пол. XIX в.', '2 пол. XIX в.'), ('1 чт. XX в.', '1 чт. XX в.')], max_length=255, unique=True, verbose_name='Датировка памятника')),
            ],
            options={
                'verbose_name': 'Датировка памятника',
                'verbose_name_plural': 'Датировка памятника',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Список организаций',
                'verbose_name_plural': 'Список организаций',
            },
        ),
        migrations.CreateModel(
            name='ResearchYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год исследования')),
            ],
            options={
                'verbose_name': 'Года раскопок',
                'verbose_name_plural': 'Года раскопок',
            },
        ),
        migrations.CreateModel(
            name='Monuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название памятника с идентификатором')),
                ('name', models.CharField(max_length=255, verbose_name='Название памятника (для пользователей)')),
                ('description', models.TextField(blank=True, default='Lorem ipsum', verbose_name='Краткое описание')),
                ('landmark', models.TextField(blank=True, default='Lorem ipsum', verbose_name='Что сейчас на месте памятника')),
                ('address', models.CharField(default='Lorem ipsum', max_length=255, verbose_name='Административный адрес')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug-name')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость записи')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('authors', models.ManyToManyField(blank=True, to='archeomap.authors', verbose_name='Авторы раскопок')),
                ('classification_category', models.ManyToManyField(to='archeomap.classification', verbose_name='Категория')),
                ('custom_category', models.ManyToManyField(blank=True, to='archeomap.customcategory', verbose_name='Дополнительная категория')),
                ('dating', models.ManyToManyField(to='archeomap.dating', verbose_name='Датировка')),
                ('organizations', models.ManyToManyField(blank=True, to='archeomap.organizations', verbose_name='Организация')),
                ('research_years', models.ManyToManyField(blank=True, to='archeomap.researchyears', verbose_name='Годы исследования')),
            ],
            options={
                'verbose_name': 'Археологические памятники',
                'verbose_name_plural': 'Археологические памятники',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=archeomap.models.utils.image_upload_to, verbose_name='Изображение')),
                ('description', models.TextField(default='Lorem ipsum', verbose_name='Подпись к картинке')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='archeomap.monuments', to_field='title')),
            ],
            options={
                'verbose_name': 'Изображения для странички с описанием памятника',
                'verbose_name_plural': 'Изображения для странички с описанием памятника',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тектовое описание единицы контента')),
                ('link', models.URLField(max_length=255, unique=True, verbose_name='Ссылка на контент')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='archeomap.monuments', to_field='title')),
            ],
            options={
                'verbose_name': 'Список аудио-видео контента для памятников',
                'verbose_name_plural': 'Список аудио-видео контента для памятников',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Библиографическая ссылка на источник')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на источник если есть')),
                ('what_is', models.CharField(blank=True, max_length=255, verbose_name='Кратко об источнике')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='archeomap.monuments', to_field='title')),
            ],
            options={
                'verbose_name': 'Список источников',
                'verbose_name_plural': 'Список источников',
            },
        ),
    ]
