# Generated by Django 5.0.4 on 2024-05-31 10:47

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcavationsSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excavation_square', django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.DecimalField(decimal_places=12, max_digits=15), size=2), blank=True, null=True, size=100)),
                ('description', models.TextField(blank=True, default='Lorem ipsum', verbose_name='Примечание, откуда взяты координаты')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excavations_square', to='archeomap.monuments', to_field='title')),
            ],
            options={
                'verbose_name': 'Координаты площади раскопок',
                'verbose_name_plural': 'Координаты площади раскопок',
            },
        ),
    ]
