# Generated by Django 5.0.4 on 2024-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='latitude',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='longitude',
            field=models.FloatField(default=10),
        ),
    ]
