# Generated by Django 5.0.4 on 2024-04-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0002_alter_classification_classification_category_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
