# Generated by Django 5.0.4 on 2024-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0002_remove_testmodel_age_testmodel_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='category',
            field=models.ManyToManyField(to='archeomap.testcategory', verbose_name='категория'),
        ),
    ]
