# Generated by Django 5.0.4 on 2025-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0003_monuments_icon_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monuments',
            name='address',
            field=models.CharField(blank=True, default='Lorem ipsum', max_length=255, verbose_name='Административный адрес'),
        ),
    ]
