# Generated by Django 5.0.4 on 2024-04-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0004_authors_classification_content_customcategory_dating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monuments',
            name='authors',
            field=models.ManyToManyField(blank=True, to='archeomap.authors', verbose_name='Авторы раскопок'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='classification_category',
            field=models.ManyToManyField(to='archeomap.classification', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='content',
            field=models.ManyToManyField(to='archeomap.content', verbose_name='Аудио-видео контент'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='custom_category',
            field=models.ManyToManyField(blank=True, to='archeomap.customcategory', verbose_name='Дополнительная категория'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='dating',
            field=models.ManyToManyField(to='archeomap.dating', verbose_name='Датировка'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='archeomap.organizations', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='research_years',
            field=models.ManyToManyField(blank=True, to='archeomap.researchyears', verbose_name='Годы исследования'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug-name'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='sources',
            field=models.ManyToManyField(to='archeomap.sources', verbose_name='Список использованных источников'),
        ),
    ]
