# Generated by Django 5.0.4 on 2024-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0005_alter_monuments_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='title',
            field=models.TextField(verbose_name='Библиографическая ссылка на источник'),
        ),
    ]
