# Generated by Django 5.0.4 on 2024-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0006_alter_sources_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='what_is',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кратко об источнике'),
        ),
        migrations.AddField(
            model_name='sources',
            name='what_is',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кратко об источнике'),
        ),
    ]
