# Generated by Django 5.0.4 on 2024-04-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0007_content_what_is_sources_what_is'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='what_is',
        ),
    ]
