# Generated by Django 5.0.4 on 2024-04-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0008_remove_content_what_is'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображения для странички с описанием памятника', 'verbose_name_plural': 'Изображения для странички с описанием памятника'},
        ),
        migrations.AlterField(
            model_name='customcategory',
            name='custom_category_value',
            field=models.CharField(choices=[('NONE', 'NONE'), ('Памятники с обозначением на местности', 'Памятники с обозначением на местности'), ('Самые выдающиеся памятники: выбор редакции', 'Самые выдающиеся памятники: выбор редакции'), ('Памятники, напрямую связанные с историческими личностями', 'Памятники, напрямую связанные с историческими личностями'), ('Первые археологические раскопки в Петербурге', 'Первые археологические раскопки в Петербурге')], max_length=255, verbose_name='Кастомная категория'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug-name'),
        ),
    ]
