# Generated by Django 5.0.4 on 2024-04-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeomap', '0009_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monuments',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug-name'),
        ),
    ]
