version: '3.1'
services:
  database_host:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 606090824
      POSTGRES_DB: archeomap_db

  backend:
    build:
      context: .
    expose:
      - 8080
    command: sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py initadmin &&
      gunicorn app.wsgi -b 0.0.0.0:8080"
    depends_on:
      - database_host

  nginx:
    build: ./.docker/nginx
    ports:
      - 8000:80
    depends_on:
      - backend
