# Generated by Django 5.0.4 on 2024-05-26 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Топик источника для админ-панели')),
                ('source', models.TextField(verbose_name='Объект библиографии (ссылка)')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на источник если есть')),
                ('what_is', models.CharField(blank=True, max_length=255, verbose_name='Кратко об источнике (пояснение для пользователя)')),
                ('publication_date', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)], verbose_name='Год публикации')),
                ('source_identificator', models.CharField(blank=True, max_length=255, verbose_name='DOI/ISBN')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug-name')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость записи')),
                ('main_category', models.CharField(choices=[('Unknown', 'Unknown'), ('Городская археология', 'Городская археология'), ('Археология Санкт-Петербурга', 'Археология Санкт-Петербурга')], default='Unknown', max_length=100, verbose_name='Главная категория (область знаний)')),
                ('sub_category', models.CharField(choices=[('Unknown', 'Unknown'), ('Книги', 'Книги'), ('Статьи', 'Статьи'), ('Образовательные видео\\Научно-популярные лекции', 'Образовательные видео\\Научно-популярные лекции'), ('Цифровые проекты', 'Цифровые проекты'), ('Законодательные акты и другие нормативные документы', 'Законодательные акты и другие нормативные документы'), ('Другое', 'Другое')], default='Unknown', max_length=100, verbose_name='Тип источника')),
            ],
            options={
                'verbose_name': 'Библиография',
                'verbose_name_plural': 'Библиография',
            },
        ),
    ]
